### ISSUE TITLE
Cap per experiment per body rather than just per body

### ISSUE THREAD

**Issue by NathanKell** [Sigma88/Sigma-ScienceBalance#1]
As Seen On IRC (tm)

The idea here is that experiments you unlock later in the tree (for example, in RP-0, you unlock the orbital perturbation instrument somewhat later) effectively extend the cap, encouraging you to use these new instruments on surveyed planets (and extending, if you will, the planet's cap).

**Comment by Sigma88** [comment]
## Revised Node Structure

<pre>
SigmaScienceBalance<b>†</b>
{
    standardMessageText<b><sup>•</sup></b> = &lt;string&gt;
    standardMessageDuration<b><sup>•</sup></b> = &lt;double&gt;
    Body
    {
        name<b><sup>•</sup>†</b> = &lt;string&gt;
        
        defaultCap<b><sup>•</sup>†</b> = &lt;double&gt;
        defaultMessageText<b><sup>•</sup></b> = &lt;string&gt;
        defaultMessageDuration<b><sup>•</sup></b> = &lt;double&gt;
        
        Experiments
        {
            cap<b><sup>•</sup>†</b> = &lt;double&gt;
            messageText<b><sup>•</sup></b> = &lt;string&gt;
            messageDuration<b><sup>•</sup></b> = &lt;string&gt;
            id<b>†</b> = &lt;string&gt;
        }
    }
}
</pre>

**Keys:**
<b><sup>•</sup></b> - Unique (First one will be chosen)
<b>†</b> - At least one is required (If missing the parent node will be removed)

**Message Syntax:**
```<cb>``` = body.displayName
```<oc>``` = "<color=" + body.orbit.color + ">"
```<id>``` = experiment.id
```<cap>``` = science cap (number) that triggered the message
```<lost>``` = science lost (number) for exceding the cap
```< >``` = ' '

**Comment by NathanKell** [comment]
then I would suggest changing 'cap' and 'message' to 'defaultCap' and 'defaultMessage' but otherwise yep makes sense!

**Comment by Sigma88** [comment]
actually I forgot, it's ***messageText*** and ***messageDuration***

I could use ***defaultMessageText*** and ***defaultMessageDuration*** if you prefere, even if it seems a bit long

**Comment by NathanKell** [comment]
Clarity >>>> long :)

**Comment by Sigma88** [comment]
fine for me :)

**Comment by Sigma88** [comment]
revised the node structure, see above

**Comment by Sigma88** [comment]
see #2
