### ISSUE TITLE
Make cap vary by Game Difficulty Setting Science slider

### ISSUE THREAD

**Issue by NathanKell** [Sigma88/Sigma-ScienceBalance#2]
If the cap is absolute, then the science difficulty setting is merely a way to speed up or slow down time rather than anything that actually changes how much science you get from a body. The cap needs to scale by the science slider.

**Comment by Sigma88** [comment]
what is the best approach for this?

is it enough to multiply the cap by the science multiplier?

Easy = 200% science = 200% cap
Hard = 60% science = 60% cap

**Comment by NathanKell** [comment]
Yep, should be that easy :)

**Comment by Sigma88** [comment]
sorry but I don't really have time to continue development on this mod

it doesn't seem like it is needed very much

if there is a strong need for this I might get back to it in the future
